---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: amancevice/superset
        ports:
        - containerPort: 8088
        volumeMounts:
        - name: superset-config
          mountPath: /app/pythonpath/superset_config.py
          subPath: superset_config.py
      volumes:
      - name: superset-config
        configMap:
          name: superset-config
---
apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  selector:
    app: superset
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8088
  type: NodePort
